// app/layout.tsx

import { AuthProvider } from '@/context/AuthContext';  // تأكد من صحة المسار
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* إضافة AuthProvider ليلف التطبيق بالكامل */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}